# Basic
edition = "2024"
use_small_heuristics = "Max"
# Imports
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
# Documentation/Comments
comment_width = 100
normalize_comments = true
wrap_comments = true
# Misc
chain_width = 80
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
