include = ["**/Cargo.toml"]

[formatting]
align_entries = false
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = false
compact_arrays = true
compact_inline_tables = false
column_width = 120
indent_tables = false
indent_string = '    '
trailing_newline = true
reorder_keys = false
allowed_blank_lines = 1
crlf = false

[[rule]]
keys = [
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "workspace.dependencies",
    "patch.crates-io",
]
formatting = { reorder_keys = true }
